from app.models import db, Comment

def seed_comments():

    com1 = Comment( userId=9, postId=10, content='<333')
    com2 = Comment( userId=12, postId=3, content='the smile! im dead')
    com3 = Comment( userId=1, postId=11, content='Call ur aunties in Vietnam. We miss u.')
    com4 = Comment( userId=14, postId=5, content='how much?')
    com5 = Comment( userId=3, postId=9, content='was it good at least?')
    com6 = Comment( userId=2, postId=4, content='YUM')
    com7 = Comment( userId=18, postId=17, content='looks good')
    com8 = Comment( userId=11, postId=1, content='must be nice')
    com9 = Comment( userId=8, postId=9, content='looks bomb')
    com10 = Comment( userId=6, postId=7, content='gross what is that')
    com11 = Comment( userId=16, postId=23, content='cute')
    com12 = Comment( userId=19, postId=26, content='i would die for kevin')
    com13 = Comment( userId=14, postId=1, content='hungry! >:(')
    com14 = Comment( userId=10, postId=14, content='lets go meatyboys')
    com15 = Comment( userId=13, postId=10, content='papa')
    com16 = Comment( userId=5, postId=24, content='WOW he touched grass xD')
    com17 = Comment( userId=7, postId=12, content='HE WOULD! queen.')
    com18 = Comment( userId=22, postId=2, content='nom nom nom')
    com19 = Comment( userId=21, postId=15, content='take this down its against community guidelines')
    com20 = Comment( userId=26, postId=12, content='you go girl')
    com21 = Comment( userId=4, postId=6, content='thats a wall dummy')
    com22 = Comment( userId=11, postId=3, content='<333')
    com23 = Comment( userId=25, postId=19, content='relatable')
    com24 = Comment( userId=23, postId=22, content='ew disney adults')
    com25 = Comment( userId=1, postId=23, content='im blushing :shyface:')
    com26 = Comment( userId=10, postId=18, content='i heard charcoal makes your poop black. can u confirm?')
    com27 = Comment( userId=24, postId=16, content='@u this sucks.')



    db.session.add(com1)
    db.session.add(com2)
    db.session.add(com3)
    db.session.add(com4)
    db.session.add(com5)
    db.session.add(com6)
    db.session.add(com7)
    db.session.add(com8)
    db.session.add(com9)
    db.session.add(com10)
    db.session.add(com11)
    db.session.add(com12)
    db.session.add(com13)
    db.session.add(com14)
    db.session.add(com15)
    db.session.add(com16)
    db.session.add(com17)
    db.session.add(com18)
    db.session.add(com19)
    db.session.add(com20)
    db.session.add(com21)
    db.session.add(com22)
    db.session.add(com23)
    db.session.add(com24)
    db.session.add(com25)
    db.session.add(com26)
    db.session.add(com27)

    db.session.commit()

def undo_comments():
    db.session.execute('TRUNCATE comments RESTART IDENTITY CASCADE;')
    db.session.commit()
