"""empty message

Revision ID: c2bf1288a982
Revises: d8cea9ddf6c7
Create Date: 2022-07-26 10:00:10.443079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2bf1288a982'
down_revision = 'd8cea9ddf6c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('posts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('profile_pic', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic')
    op.drop_column('posts', 'created_at')
    op.drop_column('comments', 'created_at')
    # ### end Alembic commands ###
